config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  post 'connect_session', to: 'customer#connect_session'
  post 'reconnect_session/:connection_id', to: 'customer#reconnect_session'
  post 'refresh_session/:connection_id', to: 'customer#refresh_session'
  post 'destroy_session/:connection_secret', to: 'customer#destroy_session'

  get 'accounts/:connection_id', to: 'customer#accounts', as: 'accounts'
  get 'transactions/:connection_id/:account_id', to: 'customer#transactions', as: 'transactions'

  root 'customer#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates_presence_of :spectre_id, :user_id

  belongs_to :user

  # def connect_session
  #   response = SpectreApiService.connect_session(self.spectre_id)
  #   response = JSON.parse response
  #   response["data"]
  # end

  # def reconnect_session(connection_id)
  #   response = SpectreApiService.reconnect_session(self.spectre_id, connection_id)
  #   response = JSON.parse response
  #   response["data"]
  # end

  # def refresh_session(connection_id)
  #   response = SpectreApiService.refresh_session(connection_id)
  #   response = JSON.parse response
  #   response["data"]
  # end

  # def fetch_connections
  #   response = SpectreApiService.fetch_connections(self.spectre_id)
  #   response = JSON.parse response
  #   response["data"]
  # end

  # def fetch_accounts(connection_id)
  #   response = SpectreApiService.fetch_accounts(connection_id)
  #   response = JSON.parse response
  #   response["data"]
  # end

  # def fetch_transactions(connection_id, account_id)
  #   response = SpectreApiService.fetch_transactions(connection_id, account_id)
  #   response = JSON.parse response
  #   response["data"]
  # end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :customer, :dependent => :destroy

  def user_id
  	id or where(email: email).id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :set_hostname


	def self.hostname
		@@hostname
	end

	private

		def set_hostname
			port = request.port ? ":#{request.port}" : ""
			@@hostname = "#{request.protocol}#{request.host}#{port}"
		end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController

	def index
		@customer = current_user.customer
		@connections = Spectre::ConnectionsApi.new(@customer.spectre_id).fetch
	end

	def connect_session
		@customer = current_user.customer
		session = Spectre::ConnectionsApi.new(@customer.spectre_id).create

		redirect_to session["connect_url"]
	end

  def reconnect_session
    @customer = current_user.customer
    session = Spectre::ConnectionsApi.new(@customer.spectre_id).reconnect(params[:connection_id])

    redirect_to session["connect_url"]
  end

  def refresh_session
    @customer = current_user.customer
    session = Spectre::ConnectionsApi.new.refresh(params[:connection_id])

    redirect_to session["connect_url"]
  end

  def destroy_session
  	@customer = current_user.customer
  	destroy = Spectre::ConnectionsApi.new.destroy(params[:connection_id], @customer.secret, params[:connection_secret])
  	
  	redirect_to root_path
  end

	def accounts
    	@accounts = Spectre::AccountsApi.new(params[:connection_id]).fetch
	end

  def transactions
    @transactions = Spectre::TransactionsApi.new(params[:connection_id]).fetch(params[:account_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	after_action :add_customer, only: :create

	private

		def add_customer
      identifier = "#{current_user.user_id}::#{current_user.email}"
      response = Spectre::CustomerApi.new(identifier).request_customer
      @customer = Mapper::Customer.response_to_customer(response)

      current_user.build_customer(@customer)
      current_user.save!
		end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
  def refresh_possible?(session)
  	return false if session["next_refresh_possible_at"].nil?

    refresh_at = session["next_refresh_possible_at"]
    Time.now >= Time.parse(refresh_at)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/customer/_connections.html.erb
<% if connections.present? %>
  <h1> Connections </h1>
	<table class="table">
    <thead>
      <tr>
        <th> ID </th>
        <th> Name </th>
        <th> Status </th>
        <th> Country Code </th>
        <th> Created At </th>
        <th> Actions </th>
      </tr>
    </thead>
		<% connections.each do |connection| %>
      <tr>
        <td> <%= connection["id"] %> </td>
        <td> <%= connection["provider_name"] %> </td>
        <td> <%= connection["status"] %> </td>
        <td> <%= connection["country_code"] %> </td>
        <td> <%= connection["created_at"] %> </td>
        <% if connection["status"] != "inactive" %>
          <td>
            <%= link_to "Accounts", accounts_path(connection["id"]) %>
            <%= button_to "Reconnect", { action: :reconnect_session, connection_id: connection["id"] } %>
            <%= button_to "Refresh", { action: :refresh_session, connection_id: connection["id"] }, :disabled => !refresh_possible?(connection) %>
            <%= button_to "Destroy", { action: :destroy_session, connection_secret: connection["secret"], connection_id: connection["id"] } %>
          </td>
        <% end %>
      </tr>
		<% end %>
	</table>
<% end %>

app/views/customer/accounts.html.erb
<% if @accounts.present? %>
    <h1> Accounts </h1>
    <table class="table">
    <thead>
      <tr>
        <th> ID </th>
        <th> Name </th>
        <th> Balance </th>
        <th> Currency </th>
        <th> Nature </th>
        <th> Actions </th>
      </tr>
    </thead>
        <% @accounts.each do |account| %>
      <tr>
        <td>
          <%= account["id"] %>
        </td>
        <td>
          <%= account["name"] %>
        </td>
        <td>
          <%= account["balance"] %>
        </td>
        <td>
          <%= account["nature"] %>
        </td>
        <td>
          <%= account["currency_code"] %>
        </td>
        <td>
          <%= link_to "Transactions", transactions_path(account["connection_id"], account["id"]) %>
        </td>
      </tr>
        <% end %>
    </table>
<% end %>

<%= render "layouts/navigation" %>

app/views/customer/index.html.erb
<%= render "connections", connections: @connections %>

<%= button_to "Create connection", { action: :connect_session } %>

app/views/customer/transactions.html.erb
<% if @transactions.present? %>
    <h1> Transactions </h1>
    <table class="table">
    <thead>
      <tr>
        <th> ID </th>
        <th> Status </th>
        <th> Made on </th>
        <th> Amount </th>
        <th> Currency Code </th>
        <th> Description </th>
      </tr>
    </thead>
        <% @transactions.each do |transaction| %>
          <tr>
            <td>
              <%= transaction["id"] %>
            </td>
            <td>
              <%= transaction["status"] %>
            </td>
            <td>
              <%= transaction["made_on"] %>
            </td>
            <td>
              <%= transaction["amount"] %>
            </td>
            <td>
              <%= transaction["currency_code"] %>
            </td>
            <td>
              <%= transaction["description"] %>
            </td>
          </tr>
        <% end %>

    </table>
<% end %>

<%= render "layouts/navigation", back: true %>

app/views/layouts/_header.html.erb
<nav id="header" class="navbar has-shadow">
  <div class="navbar-brand">
    <div class="navbar-menu">
      <div class="navbar-start">

        <% unless current_user.nil? or current_user.customer.nil? %>
          <span class="navbar-item">
            <b>Customer ID: </b>
            <%= current_user.customer.spectre_id %>
          </span>
        <% end %>

      </div>

    </div>
  </div>
  
  <div class="navbar-end">

    <% if user_signed_in? %>
      <span class="navbar-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      </span>
    <% else %>
      <span class="navbar-item">
        <%= link_to 'Sign In', new_user_session_path %>
      </span>
      <span class="navbar-item">
        <%= link_to 'Sign Up', new_user_registration_path %>
      </span>
    <% end %>

  </div>
</nav>

app/views/layouts/_navigation.html.erb
<span>
	<% if defined? back %>
    <%= link_to "Back", :back %>    
	<% end %>

	<%= link_to "Connections", root_path %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% unless notice.nil? %>
      <p class="notification"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="notification is-warning"><%= alert %></p>
    <% end %>

    <div class="app-container">
      <%= render 'layouts/header' %>

      <%= yield %>
    </div>
  </body>
</html>

<!-- TODO: Make wise -->